### ISSUE TITLE
Enable ttl for cache table

### ISSUE THREAD

**Issue by Jeff-Tian** [Jeff-Tian/serverless-space#19]
https://uniheart.atlassian.net/browse/UNI-47

**Comment by Jeff-Tian** [comment]
Now timeout is 15 min:

<img width="1416" alt="image" src="https://user-images.githubusercontent.com/3367820/182844590-589d7daf-2073-47ab-9855-4fbb374635ec.png">

**Comment by Jeff-Tian** [comment]
Dynamo DB cache table:


| Before | After |
| ----   | ----- |
|<img width="1400" alt="image" src="https://user-images.githubusercontent.com/3367820/182844712-fdcbb181-d750-4c85-b91c-648cb1cc4ba8.png"> | |

**Comment by Jeff-Tian** [comment]
```


2022-08-04T20:17:43.445+08:00复制2022-08-04T12:17:43.444Z	8927dfc0-9f2a-44bf-88de-5f61fff88ac3	ERROR	ensureTtl error:  MissingRequiredParameter: Missing required key 'TableName' in params    at ParamValidator.fail (/opt/nodejs/node_modules/aws-sdk/lib/param_validator.js:50:37)    at ParamValidator.validateStructure (/opt/nodejs/node_modules/aws-sdk/lib/param_validator.js:61:14)    at ParamValidator.validateMember (/opt/nodejs/node_modules/aws-sdk/lib/param_validator.js:88:21)    at ParamValidator.validate (/opt/nodejs/node_modules/aws-sdk/lib/param_validator.js:34:10)    at Request.VALIDATE_PARAMETERS (/opt/nodejs/node_modules/aws-sdk/lib/event_listeners.js:132:42)    at Request.callListeners (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:106:20)    at callNextListener (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:96:12)    at /opt/nodejs/node_modules/aws-sdk/lib/event_listeners.js:86:9    at finish (/opt/nodejs/node_modules/aws-sdk/lib/config.js:386:7)    at /opt/nodejs/node_modules/aws-sdk/lib/config.js:404:9 {  code: 'MissingRequiredParameter',  time: 2022-08-04T12:17:43.444Z} | 2022-08-04T12:17:43.444Z 8927dfc0-9f2a-44bf-88de-5f61fff88ac3 ERROR ensureTtl error: MissingRequiredParameter: Missing required key 'TableName' in params at ParamValidator.fail (/opt/nodejs/node_modules/aws-sdk/lib/param_validator.js:50:37) at ParamValidator.validateStructure (/opt/nodejs/node_modules/aws-sdk/lib/param_validator.js:61:14) at ParamValidator.validateMember (/opt/nodejs/node_modules/aws-sdk/lib/param_validator.js:88:21) at ParamValidator.validate (/opt/nodejs/node_modules/aws-sdk/lib/param_validator.js:34:10) at Request.VALIDATE_PARAMETERS (/opt/nodejs/node_modules/aws-sdk/lib/event_listeners.js:132:42) at Request.callListeners (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:106:20) at callNextListener (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:96:12) at /opt/nodejs/node_modules/aws-sdk/lib/event_listeners.js:86:9 at finish (/opt/nodejs/node_modules/aws-sdk/lib/config.js:386:7) at /opt/nodejs/node_modules/aws-sdk/lib/config.js:404:9 { code: 'MissingRequiredParameter', time: 2022-08-04T12:17:43.444Z }
-- | --



```

**Comment by Jeff-Tian** [comment]
```
<html>
<body>
<!--StartFragment-->

2022-08-05T12:23:03.347+08:00复制2022-08-05T04:23:03.347Z	86e30a70-8c02-47a7-8a95-3e37e5c717a8	ERROR	ensureTtl error:  AccessDeniedException: User: arn:aws:sts::443862765029:assumed-role/serverless-space-dev-us-east-1-lambdaRole/serverless-space-dev-nest is not authorized to perform: dynamodb:UpdateTimeToLive on resource: arn:aws:dynamodb:us-east-1:443862765029:table/cache-table because no identity-based policy allows the dynamodb:UpdateTimeToLive action    at Request.extractError (/opt/nodejs/node_modules/aws-sdk/lib/protocol/json.js:52:27)    at Request.callListeners (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:106:20)    at Request.emit (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:78:10)    at Request.emit (/opt/nodejs/node_modules/aws-sdk/lib/request.js:686:14)    at Request.transition (/opt/nodejs/node_modules/aws-sdk/lib/request.js:22:10)    at AcceptorStateMachine.runTo (/opt/nodejs/node_modules/aws-sdk/lib/state_machine.js:14:12)    at /opt/nodejs/node_modules/aws-sdk/lib/state_machine.js:26:10    at Request.<anonymous> (/opt/nodejs/node_modules/aws-sdk/lib/request.js:38:9)    at Request.<anonymous> (/opt/nodejs/node_modules/aws-sdk/lib/request.js:688:12)    at Request.callListeners (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:116:18) {  code: 'AccessDeniedException',  time: 2022-08-05T04:23:03.345Z,  requestId: '0GIA56OM7EU75KD644FTDJCFR7VV4KQNSO5AEMVJF66Q9ASUAAJG',  statusCode: 400,  retryable: false,  retryDelay: 32.305729854134135} | 2022-08-05T04:23:03.347Z 86e30a70-8c02-47a7-8a95-3e37e5c717a8 ERROR ensureTtl error: AccessDeniedException: User: arn:aws:sts::443862765029:assumed-role/serverless-space-dev-us-east-1-lambdaRole/serverless-space-dev-nest is not authorized to perform: dynamodb:UpdateTimeToLive on resource: arn:aws:dynamodb:us-east-1:443862765029:table/cache-table because no identity-based policy allows the dynamodb:UpdateTimeToLive action at Request.extractError (/opt/nodejs/node_modules/aws-sdk/lib/protocol/json.js:52:27) at Request.callListeners (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:106:20) at Request.emit (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:78:10) at Request.emit (/opt/nodejs/node_modules/aws-sdk/lib/request.js:686:14) at Request.transition (/opt/nodejs/node_modules/aws-sdk/lib/request.js:22:10) at AcceptorStateMachine.runTo (/opt/nodejs/node_modules/aws-sdk/lib/state_machine.js:14:12) at /opt/nodejs/node_modules/aws-sdk/lib/state_machine.js:26:10 at Request.<anonymous> (/opt/nodejs/node_modules/aws-sdk/lib/request.js:38:9) at Request.<anonymous> (/opt/nodejs/node_modules/aws-sdk/lib/request.js:688:12) at Request.callListeners (/opt/nodejs/node_modules/aws-sdk/lib/sequential_executor.js:116:18) { code: 'AccessDeniedException', time: 2022-08-05T04:23:03.345Z, requestId: '0GIA56OM7EU75KD644FTDJCFR7VV4KQNSO5AEMVJF66Q9ASUAAJG', statusCode: 400, retryable: false, retryDelay: 32.305729854134135 }
-- | --


<!--EndFragment-->
</body>
</html>
```
